version: '3.8'
services:
  proxy-demo:
    restart: unless-stopped
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-proxy:latest"
    ports:
      - "8000:8000"
    depends_on:
      - client
      - server
  server:
    restart: unless-stopped
    build:
      context: ./server-demo
      target: production
    env_file: .env
    environment:
      NODE_ENV: production
  client:
    restart: unless-stopped
    depends_on:
      - server
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-client:latest"

