- name: Re install agent on targeted device
  hosts: all
  become: true
  gather_facts: false
  vars:
    base_path: /opt/squirrelserversmanager

  tasks:
    - name: Install agent on targeted device
      ansible.builtin.debug:
        msg: Host ID {{ _ssm_deviceId }} with API URL {{ _ssm_masterNodeUrl }}

    - name: Check if NodeJS does exist
      ansible.builtin.raw: which node
      check_mode: false
      changed_when: false
      failed_when: which_res_node.rc > 1
      register: which_res_node

    - name: Check if NPM does exist
      ansible.builtin.raw: which npm
      check_mode: false
      changed_when: false
      failed_when: which_res_npm.rc > 1
      register: which_res_npm

    - name: Install "PM2" node.js package globally.
      community.general.npm:
        name: pm2
        global: true
        state: latest

    - name: Install PM2 LogRotate
      command: pm2 install pm2-logrotate

    - name: Check out agent
      ansible.builtin.git:
        force: true
        repo: 'https://github.com/SquirrelCorporation/SquirrelServersManager-Agent.git'
        dest: "{{ base_path }}"
      timeout: 600

    - name: Stop PM2 Agent if running
      command: pm2 stop agent
      ignore_errors: yes

    - name: Delete PM2 Agent if present
      command: pm2 delete agent
      ignore_errors: yes

    - name: Clean directory
      command:
        chdir: "{{ base_path }}"
        cmd: rm -f ssm-agent && rm -f agent.blob && rm -rf ./build && rm -f ./hostid.txt

    - name: Write Node Url in .env file
      copy:
        content: "API_URL_MASTER={{ _ssm_masterNodeUrl }}"
        dest: "{{ base_path }}/.env"

    - name: Write HostId in hostid.txt file
      copy:
        content: "{{ _ssm_deviceId }}"
        dest: "{{ base_path }}/hostid.txt"

    - name: NPM install
      command:
        chdir: "{{ base_path }}"
        cmd: npm install

    - name: NPM run build
      command:
        chdir: "{{ base_path }}"
        cmd: npm run build

    - name: Start PM2 Agent
      command:
        chdir: "{{ base_path }}"
        cmd: pm2 start -f "./build/agent.js"

    - name: Install PM2 on startup
      command: pm2 startup

    - name: Save Agent on startup
      command: pm2 save

    - name: Save Agent on startup
      command: pm2 update

