- name: Restart agent on targeted device
  hosts: all
  become: true
  gather_facts: false
  vars:
    base_path: /opt/squirrelserversmanager

  tasks:
    - name: Stop PM2 Agent if running
      command: pm2 stop agent
      ignore_errors: yes

    - name: Delete PM2 Agent if present
      command: pm2 delete agent
      ignore_errors: yes

    - name: Start PM2 Agent
      command:
        chdir: "{{ base_path }}"
        cmd: pm2 start -f "./build/agent.js"

    - name: Install PM2 on startup
      command: pm2 startup

    - name: Save Agent on startup
      command: pm2 save

    - name: Save Agent on startup
      command: pm2 update
