- name: Uninstall agent on targeted device
  hosts: all
  become: true
  gather_facts: false
  vars:
    shell_script: undef
    agent_log_path: "{{ _ssm_agentLogPath | default(omit) }}"

  tasks:
    - name: Manage PM2 Agent
      block:
        - name: Stop PM2 Agent if running
          command: pm2 stop agent
          ignore_errors: true

        - name: Delete PM2 Agent if present
          command: pm2 delete agent
          ignore_errors: true

    - name: Remove Agent Directory
      block:
        - name: Recursively remove Squirrel Servers Manager directory
          ansible.builtin.file:
            path: /opt/squirrelserversmanager
            state: absent
          timeout: 600

        - name: Delete the log directory
          ansible.builtin.file:
            path: "{{ agent_log_path }}"
            state: absent
          ignore_errors: true
          when: agent_log_path is defined and agent_log_path | regex_search('/logs')

    - name: Task completion summary
      debug:
        msg: "Agent uninstallation completed on {{ inventory_hostname }}"
