- name: Uninstall agent on targeted device
  hosts: all
  become: true
  gather_facts: false
  vars:
    shell_script: undef

  tasks:
    - name: Stop PM2 Agent if running
      command: pm2 stop agent
      ignore_errors: yes

    - name: Delete PM2 Agent if present
      command: pm2 delete agent
      ignore_errors: yes

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /opt/squirrelserversmanager
        state: absent
      timeout: 600
