---
- name: Install Proxmox VE
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure wget is installed
      ansible.builtin.apt:
        name: wget
        state: present
        update_cache: yes

    - name: Add Proxmox VE repository
      ansible.builtin.apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
        state: present

    - name: Add Proxmox VE GPG key
      ansible.builtin.command: >
        wget -qO- https://enterprise.proxmox.com/debian/proxmox-release-6.x.gpg | apt-key add -
      args:
        creates: /etc/apt/trusted.gpg.d/proxmox-release-6.x.gpg

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Proxmox VE and dependencies
      ansible.builtin.apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
        state: present

    - name: Ensure kernel support for virtualization
      ansible.builtin.apt:
        name: linux-virtual
        state: present

    - name: Remove old kernels
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ ansible_kernel_packages }}"
      when: '"pve" not in ansible_kernel_packages'

    - name: Enable and start Proxmox VE services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - pve-cluster
        - pvedaemon
        - pveproxy
        - pvestatd

    - name: Reboot the server to apply changes
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for Proxmox VE installation."
        when: not ansible_check_mode
